#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh --shapes

bspc monitor eDP -n center
bspc monitor HDMI-A-0 -n left

bspc monitor center -d I II III IV V 
bspc monitor left -d VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           4
bspc config border_radius	 12

bspc config split_ratio          0
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Chromium desktop='^2'
bspc rule -a Google-chrome desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Xfce4-terminal desktop='^4'
bspc rule -a code-oss desktop='^4'
bspc rule -a Postman desktop='^4'
bspc rule -a TelegramDesktop desktop='^5'
bspc rule -a discord desktop='^5'
bspc rule -a whatsapp-nativefier-d52542 desktop='^5'
bspc rule -a PacketTracer desktop='^4'

